Bug/fix create class
IC-TestIt/Front-End pull request #11
Opened 2017-07-25 03:31 UTC by medson10

2017-07-25 03:31 UTC, medson10 commented
Consegui fazer a table funcionar

2017-07-25 14:06 UTC, Vitormdias requested changes

2017-07-25 14:06 UTC, Vitormdias commented on src/components/CreateClass.vue
> +      this.room.teacherId = 6
teacherId a partir do usuario logado

2017-07-26 03:17 UTC, Vitormdias requested changes
Salvar também o studentId

2017-07-26 03:19 UTC, Vitormdias commented
Resolver conflitos com a master por favor

2017-07-26 04:06 UTC, Vitormdias approved these changes

2017-07-26 04:07 UTC, merged