Feat/minha prova nao corrigida
IC-TestIt/Front-End pull request #113
Opened 2017-11-10 02:42 UTC by medson10

2017-11-10 02:43 UTC, medson10 commented
![image](https://user-images.githubusercontent.com/17956325/32640500-1432722e-c5b0-11e7-9569-3a8269c20d52.png)

2017-11-10 11:48 UTC, Vitormdias requested changes

2017-11-10 11:48 UTC, Vitormdias commented on src/components/MyTests.vue
> +          if (r.status === 200) {
Esse bloco de código se repete em todas condições, deixa em uma função

2017-11-10 11:51 UTC, Vitormdias requested changes

2017-11-10 11:51 UTC, Vitormdias commented on src/components/MyTestConclusionCard.vue
> +        if (grade <= 40) {
Aqui as cores, a gente tem que colocar de acordo com o total, um pouco mais chato que isso o calculo dai, mas assim, as faixas de cor devem ser:
- 0-40%
- 41%-70%
- 70%-100%

Fica melhor dai

2017-11-13 16:16 UTC, Vitormdias approved these changes

2017-11-13 16:16 UTC, merged