Realiza dialog de finalizar prova
IC-TestIt/Front-End pull request #117
Opened 2017-11-14 16:48 UTC by matheusnovais95

![image](https://user-images.githubusercontent.com/18332845/32792609-e8bb63aa-c94a-11e7-92fe-7204ed12b454.png)

2017-11-14 16:56 UTC, Vitormdias requested changes

2017-11-14 16:56 UTC, Vitormdias commented on src/components/CorrectTests.vue
> +      let answered = []
cara esse código não vai funcionar, pq o answered  ta vazio, faz o seguinte vc tem que pegar o objeto que ta as listas, e ai dar o .every nesse

2017-11-14 16:56 UTC, Vitormdias commented on src/components/CorrectTests.vue
> +        return true
só da return answered.every((item) => item.isQuestionCorrected), pq essa função retorna boolean então não faz sentido isso, entendeu?

2017-11-16 13:06 UTC, matheusnovais95 commented on src/components/CorrectTests.vue
> +        return true
blz, entendi

2017-11-16 17:00 UTC, Vitormdias approved these changes

2017-11-16 17:00 UTC, merged