Feat/dashboard aluno
IC-TestIt/Front-End pull request #118
Opened 2017-11-17 01:35 UTC by medson10

2017-11-17 01:37 UTC, medson10 commented
![image](https://user-images.githubusercontent.com/17956325/32925056-02e83f0e-cb27-11e7-80e9-020e2dc0b24b.png)

2017-11-17 18:42 UTC, Vitormdias requested changes
Então as provas do lado direito cara, é do futuro, as que ele tem pra fazer agora e as que vão rolar no futuro

2017-11-17 18:42 UTC, Vitormdias commented on src/components/StudentDashboard/ClassCard.vue
> +  props: ['room'],
trocar para currentClass

2017-11-17 20:54 UTC, medson10 commented
![image](https://user-images.githubusercontent.com/17956325/32968432-579e06e0-cbc8-11e7-8369-051fd631f8dd.png)

2017-11-17 20:54 UTC, medson10 commented
@Vitormdias feito

2017-11-18 15:59 UTC, Vitormdias requested changes
Eu não vi se você mudou isso, mas tava com duas chamadas no dashboard do professor da mesma rota, tinha que mudar isso, consegue ajeitar isso? pra chamar uma vez só

2017-11-18 15:59 UTC, Vitormdias commented on src/components/StudentDashboard/CurrentClass.vue
>    props: ['room'],
cara era pra trocar a prop hauhau, ta room

2017-11-18 17:38 UTC, Vitormdias approved these changes

2017-11-18 17:38 UTC, merged