Feat/correcao prova
IC-TestIt/Front-End pull request #119
Opened 2017-11-18 20:35 UTC by medson10

2017-11-18 20:36 UTC, medson10 commented
![image](https://user-images.githubusercontent.com/17956325/32984529-52ed51ce-cc8f-11e7-8e9a-60381694ad65.png)

2017-11-18 20:36 UTC, medson10 commented
![image](https://user-images.githubusercontent.com/17956325/32984533-6e672aa6-cc8f-11e7-9b7e-2e3e500b7f26.png)

2017-11-18 20:43 UTC, Vitormdias requested changes
Quando a questão for alternativa, não vejo sentido em mostrar a resposta do professor daquele jeito, acho melhor já mostrar do jeito que a gente falou, marca a que o aluno escolheu ai a alternativa certa marca com verde o texto e caso o aluno tenha errado marca a resposta dele com vermelho

2017-11-18 20:43 UTC, Vitormdias commented on src/components/TestCorrection/Main.vue
> +<template lang="html">
Componente ta muito gigante, melhor separar em componentes menores

2017-11-18 20:43 UTC, Vitormdias commented on src/components/TestCorrection/GradeCard.vue
> +<template>
Esse cara pode ser usar em algum outro lugar? Se deixar mais genérico ou desse jeito mesmo

2017-11-18 23:13 UTC, medson10 commented on src/components/TestCorrection/GradeCard.vue
> +<template>
Desse jeito msm pode

2017-11-19 01:49 UTC, Vitormdias approved these changes

2017-11-19 01:51 UTC, medson10 commented
![image](https://user-images.githubusercontent.com/17956325/32986534-550ec592-ccbb-11e7-8f91-1d693f3cfd64.png)

2017-11-19 01:52 UTC, merged