pasta dashboard incluida
IC-TestIt/Front-End pull request #16
Opened 2017-08-08 17:28 UTC by matheusnovais95

2017-08-08 17:31 UTC, Vitormdias requested changes
Transformar em componentes, reutilizar códigos já feitos

2017-08-12 17:18 UTC, medson10 requested changes
Apaga a pasta dashboard e atualiza sua branch com a master

2017-08-12 17:18 UTC, medson10 commented on index.html
>      <link rel="stylesheet" href="https://unpkg.com/vue-material@0.7.4/dist/vue-material.css">
Seu index.html ta desatualizado, não tem mais essa referencia

2017-08-12 17:18 UTC, medson10 commented on dashboard/index.html
> +<!DOCTYPE html>
Apaga essa pasta dashboard, ela não pode ta aqui

2017-08-12 17:20 UTC, Vitormdias commented on dashboard/index.html
> +<!DOCTYPE html>
Eu vou atualizar aqui a branch dele, é pq tava dando uns problemas aqui

2017-08-16 03:32 UTC, Vitormdias commented
Acho melhor fazer outra branch, por que vai ficar muito atras esse PR, acho q é bacana @matheusnovais95 você fazer o checkout da master de novo e criar uma branch nova, pra não ter que ficar resolvendo conflitos, e ai vc pega as suas mudanças e adapta pro novo.

2017-08-16 03:32 UTC, closed without merging