Feat/add view test
IC-TestIt/Front-End pull request #24
Opened 2017-08-17 05:25 UTC by medson10

2017-08-17 05:27 UTC, medson10 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Tela Visualizar Prova](https://trello.com/c/hUPIoPpd/107-tela-visualizar-prova)

2017-08-17 12:12 UTC, Vitormdias requested changes

2017-08-17 12:12 UTC, Vitormdias commented on src/components/ViewTest.vue
> +          <div class="viewTest-AlternativeCircle pa-2 print" v-if="question.alternatives !== undefined" v-for="a in question.alternatives" :key="a.key">
Transformar em componente talvez, Acha que a gente pode reutilizar isso em algum momento?

2017-08-17 12:12 UTC, Vitormdias commented on src/router/index.js
> +    // beforeEnter: onlyTeacher
Remover comentario

2017-08-17 15:12 UTC, medson10 commented on src/components/ViewTest.vue
> +          <div class="viewTest-AlternativeCircle pa-2 print" v-if="question.alternatives !== undefined" v-for="a in question.alternatives" :key="a.key">
Talvez no exportar

2017-08-19 21:35 UTC, Vitormdias commented on src/router/index.js
> +    // beforeEnter: onlyTeacher
remover comentario

2017-08-20 04:45 UTC, medson10 commented
Mudei o icone de questão correta para um com circulo e um x no meio, também tem um com um ponto no meio, fica igual um radio selecionado

2017-08-20 22:07 UTC, Vitormdias approved these changes

2017-08-20 22:07 UTC, merged