Feat/realizar prova
IC-TestIt/Front-End pull request #36
Opened 2017-09-01 17:45 UTC by matheusnovais95

2017-09-03 22:51 UTC, Vitormdias requested changes

2017-09-03 22:51 UTC, Vitormdias commented on config/dev.env.js
> +  API: '"http://localhost:8080"',
59927 é a porta certa

2017-09-03 22:51 UTC, Vitormdias commented on src/components/negocioooooooooo.vue
> +<template>
não pode commitar arquivos assim

2017-09-03 22:51 UTC, Vitormdias commented on src/router/index.js
> +    name: 'DoTest',
RealizeExam esse é o nome certo

2017-09-04 01:07 UTC, matheusnovais95 commented on src/components/negocioooooooooo.vue
> +<template>
ja tava, alguem ja tinha commitado isso

2017-09-04 01:10 UTC, Vitormdias commented on src/components/negocioooooooooo.vue
> +<template>
cara, no git tem histórico, esse arquivo nunca esteve aqui

2017-09-07 08:00 UTC, medson10 approved these changes

2017-09-07 08:02 UTC, Vitormdias approved these changes

2017-09-07 08:03 UTC, merged