Feat/botoes avaliacao
IC-TestIt/Front-End pull request #43
Opened 2017-09-08 05:06 UTC by medson10

2017-09-08 12:17 UTC, Vitormdias approved these changes

2017-09-09 02:48 UTC, Vitormdias requested changes
Não permitir que o aluno responda depois que a prova for enviada para o professor, usar lógica do alert usado no timer

2017-09-11 20:08 UTC, medson10 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Integração botões - (Salvar e Entregar)](https://trello.com/c/8XIc1Hzj/158-integra%C3%A7%C3%A3o-bot%C3%B5es-salvar-e-entregar)

2017-09-15 01:15 UTC, Vitormdias approved these changes

2017-09-15 01:15 UTC, merged