Feat/minhas turmas
IC-TestIt/Front-End pull request #45
Opened 2017-09-13 19:07 UTC by matheusnovais95

2017-09-13 19:15 UTC, Vitormdias requested changes

2017-09-13 19:15 UTC, Vitormdias commented on src/router/index.js
> +  },
inserir um beforeEnter: onlyTeacher

2017-09-14 03:29 UTC, medson10 requested changes

2017-09-14 03:29 UTC, medson10 commented on src/components/MyClasses.vue
> +              description: item.description,
ta faltando o size, insira uma propertie size: item.size

2017-09-14 03:29 UTC, medson10 commented on src/components/MyClasses.vue
> +                <v-card class="indigo lighten-1 white--text ma-5 text-xs-center">
Todos os cards estão da mesma cor, muda pra ficar de cores diferentes igual ta na tela minhas provas

2017-09-14 03:29 UTC, medson10 commented on src/components/MyClasses.vue
> +                <h3 class="my-tests-title text-xs-center ma-1 pt-4">Minhas Turmas</h3>
Coloca cor nesse title. Quando vc entra na tela sem vir de nenhuma outra ele ta cinza, seta pra ficar na cor #006.

2017-09-15 00:18 UTC, medson10 requested changes

2017-09-15 00:18 UTC, medson10 commented on src/components/MyClasses.vue
> +                <h3 class="indigo lighten-2 my-tests-title text-xs-center ma-1 pt-4">Minhas Turmas</h3>
Essa class indigo lighten-2 deixa o fundo da tag dessa cor, a cor dessa tag vc tem q setar com css

2017-09-15 19:45 UTC, Vitormdias approved these changes

2017-09-17 14:54 UTC, merged