Imp/adicionar questao
IC-TestIt/Front-End pull request #48
Opened 2017-09-19 22:39 UTC by medson10

2017-09-21 13:23 UTC, Vitormdias requested changes

2017-09-21 13:23 UTC, Vitormdias commented on src/components/AddQuestions.vue
> +          question.keywords = question.keywords.reduce((total, k) => total + ', ' + k)
remover espaço, deixar somente ','

2017-09-21 13:58 UTC, Vitormdias requested changes

2017-09-21 13:58 UTC, Vitormdias commented on src/components/AddQuestions.vue
> +                  <v-btn class="indigo" v-on:click="addKeyword()" v-if="!currentQuestion.isAlternative" dark>Adicionar Palavra-Chave</v-btn>
trocar por botão com o ícone '+' ou botão flutuante, algo menor

2017-09-21 13:59 UTC, Vitormdias commented on src/components/AddQuestions.vue
> +                  <v-btn class="indigo" v-on:click="addKeyword()" v-if="!currentQuestion.isAlternative" dark>Adicionar Palavra-Chave</v-btn>
# BUG

![image](https://user-images.githubusercontent.com/18128585/30699722-e253c05c-9ebb-11e7-8fbb-f8aa2db3544e.png)

2017-09-21 14:00 UTC, Vitormdias commented on src/components/AddQuestions.vue
> +                  <v-btn class="indigo" v-on:click="addKeyword()" v-if="!currentQuestion.isAlternative" dark>Adicionar Palavra-Chave</v-btn>
Além disso ainda tenho que dar scroll, então talvez seja melhor diminuir os 2 primeiros campos, e deixar lado a lado

2017-09-21 14:03 UTC, Vitormdias commented on src/components/AddQuestions.vue
> +                  <v-btn class="indigo" v-on:click="addKeyword()" v-if="!currentQuestion.isAlternative" dark>Adicionar Palavra-Chave</v-btn>
colocar o botão adicionar questão de outra maneira, talvez com um icone de mais perto da lista dinamica, algo do tipo

2017-09-21 14:03 UTC, Vitormdias commented on src/components/AddQuestions.vue
> +                  <v-btn class="indigo" v-on:click="addKeyword()" v-if="!currentQuestion.isAlternative" dark>Adicionar Palavra-Chave</v-btn>
e o remover do lado superior direito

2017-09-21 14:07 UTC, Vitormdias commented on src/components/AddQuestions.vue
> +                  <v-btn class="indigo" v-on:click="addKeyword()" v-if="!currentQuestion.isAlternative" dark>Adicionar Palavra-Chave</v-btn>
Acho q esse botões não tem mta finalidade, pode fazer a ação q dispara nele em qualquer um dos abaixo

![image](https://user-images.githubusercontent.com/18128585/30700010-b3ef1cd8-9ebc-11e7-9086-31386f3fbf3f.png)

2017-09-21 14:07 UTC, Vitormdias commented on src/components/AddQuestions.vue
> +                  <v-btn class="indigo" v-on:click="addKeyword()" v-if="!currentQuestion.isAlternative" dark>Adicionar Palavra-Chave</v-btn>
Quando apertei nele voltou pro primeiro step, não ficou legal

2017-09-22 12:49 UTC, Vitormdias commented
![image](https://user-images.githubusercontent.com/18128585/30745097-42ec61de-9f7b-11e7-80ec-59244d836d0e.png)

Essa região ta mto poluida e esparsa

2017-09-22 12:54 UTC, Vitormdias commented
![image](https://user-images.githubusercontent.com/18128585/30745294-ee485d12-9f7b-11e7-8526-43b3bdf8948f.png)

Ta dando palavra inválida quando escrevo uma letra ou um numero, acho melhor mudar a regra, usando regex num ou char

2017-09-22 13:04 UTC, Vitormdias commented
O botão de -, quando eu aperto ele não remove o cara que eu to, remove o proximo

2017-09-22 13:09 UTC, Vitormdias commented
![image](https://user-images.githubusercontent.com/18128585/30745855-13020a34-9f7e-11e7-867e-c1a57693e651.png)

isso fica do lado direito

2017-09-22 13:13 UTC, Vitormdias commented
Deixa o + e - embaixo da paginação, e deixa os 2 alinhado no esquerdo superior

2017-09-22 13:13 UTC, Vitormdias commented
O salvar tem que sair, pq a gente salva todas as questões, tem que repensar o envio

2017-09-25 01:49 UTC, medson10 commented
![image](https://user-images.githubusercontent.com/17956325/30788284-254e6c52-a170-11e7-99f7-7f0180aefd2e.png)

2017-09-25 04:53 UTC, Vitormdias commented
Então ainda não ta claro q são pra adicionar questão, talvez deixar button normal, talvez no lado direito superior deixar um excluir questão, e o adicionar não sei, o ideal ia ser um ícone dentro do pagination com + ao invés do número

2017-09-25 04:54 UTC, Vitormdias commented
mas talvez seja valido revisar o layout inteiro, pedir opinião de terceiros

2017-09-25 04:56 UTC, medson10 commented
Talvez, to a muito tempo nessa task, e o editar questões ta la ainda, talvez seja melhor separar uma task para revisar esse layout e por enquanto só deixar funcional

2017-09-25 12:32 UTC, Vitormdias commented
Pode ser então, mas é importante que esteja bem feita essa tela ai

2017-09-25 12:33 UTC, Vitormdias commented
Tenta dar uma desacoplada nesse cara, pq ta mto gigante, talvez deixar alguns metodos mais genericos em um utils, algo assim

2017-09-27 03:48 UTC, Vitormdias approved these changes

2017-09-27 03:49 UTC, merged