Feat/botões prova
IC-TestIt/Front-End pull request #57
Opened 2017-09-24 14:53 UTC by medson10

2017-09-24 15:03 UTC, Vitormdias requested changes
Esse dialog é melhor transformar em componente, a gente usa ele 2x

2017-09-24 15:05 UTC, medson10 commented
Será ? Não sei se duas vezes é o bastante para transformar em componente

2017-09-24 15:35 UTC, Vitormdias commented
Eu acho que é melhor sim, pode ser que tenha mais, e é bastante código, não componentiza atrapalha na manutenção de 2 componentes

2017-09-25 02:43 UTC, medson10 commented
Problema a função de salvar é diferente em cada um

2017-09-25 04:48 UTC, Vitormdias commented
Função como prop, q nem o sign in

2017-09-26 13:15 UTC, Vitormdias approved these changes

2017-09-26 13:15 UTC, merged