Adiciona Titulo-Turma
IC-TestIt/Front-End pull request #60
Opened 2017-09-26 23:26 UTC by LuizGuilhermeSoares

2017-09-26 23:27 UTC, LuizGuilhermeSoares commented
![image](https://user-images.githubusercontent.com/18295170/30888835-182fe3e0-a2f9-11e7-821c-9745b8460685.png)

2017-09-26 23:57 UTC, Vitormdias commented on src/components/RealizeExam.vue
> +            <h2 class='realizeExam-exam-title'>{{ exam.title }} - {{ exam.description }}</h2>
Pode deixar no mesmo {{ }}

2017-09-26 23:58 UTC, Vitormdias requested changes

2017-09-26 23:58 UTC, Vitormdias commented on src/components/RealizeExam.vue
> +            <h2 class='realizeExam-exam-title'>{{ exam.title }} - {{ exam.description }}</h2>
Pode deixar no mesmo {{ }}

2017-09-27 00:24 UTC, Vitormdias approved these changes

2017-09-27 00:24 UTC, merged