Combobox canto superior direito
IC-TestIt/Front-End pull request #78
Opened 2017-10-08 20:55 UTC by matheusnovais95

2017-10-08 21:48 UTC, medson10 requested changes

2017-10-08 21:48 UTC, medson10 commented on config/dev.env.js
> +  API: '"http://localhost:8080"',
Porta da API não pode ser a 8080

2017-10-08 23:01 UTC, Vitormdias commented
![](https://github.trello.services/images/mini-trello-icon.png) [Filtro de provas da tela minhas provas](https://trello.com/c/rDegsD8R/219-filtro-de-provas-da-tela-minhas-provas)

2017-10-10 05:38 UTC, medson10 commented
Filtro implementado e funcionando, unico problema é que ainda não consegui fazer o filtro multiplo funcionar

2017-10-10 23:45 UTC, Vitormdias approved these changes

2017-10-10 23:46 UTC, merged

2017-10-11 00:01 UTC, Vitormdias commented
Resolve issue #73