Feat/dialog turmas
IC-TestIt/Front-End pull request #81
Opened 2017-10-14 00:18 UTC by medson10

Só falta integrar, to esperando a rota ficar pronta

2017-10-16 11:41 UTC, Vitormdias requested changes
Prints de tela

2017-10-16 14:51 UTC, medson10 commented
![image](https://user-images.githubusercontent.com/17956325/31618431-aebab930-b270-11e7-9df1-238855087418.png)

2017-10-16 19:59 UTC, Vitormdias requested changes
1 - Cor nos botões
2 - Transformar em ícones com title (no hover) em cada um
3 - Quando não existir deixar o botão apenas desabilitado
4 - Os botões devem ser apenas quadrados com ícones e aparecer juntos

2017-10-18 19:12 UTC, Vitormdias approved these changes

2017-10-18 19:12 UTC, merged