Feat/layout corrigir prova
IC-TestIt/Front-End pull request #82
Opened 2017-10-15 16:32 UTC by matheusnovais95

2017-10-15 17:00 UTC, matheusnovais95 commented
![image](https://user-images.githubusercontent.com/18332845/31587062-6ab1ddc0-b1b9-11e7-94c4-1f34c3188e55.png)

2017-10-16 11:45 UTC, Vitormdias requested changes

2017-10-16 11:45 UTC, Vitormdias commented on config/dev.env.js
> +  API: '"http://localhost:8080"',
Por favor parar de alterar isso

2017-10-16 11:45 UTC, Vitormdias commented on config/dev.env.js
> +  API: '"http://localhost:8080"',
Caso altere, é só não comitar

2017-10-16 11:45 UTC, Vitormdias commented on src/components/CorrectTests.vue
> +<template>
Voce não colocou as setas para navegar pelo nome do aluno o indicador de quantos alunos faltam, além disso alguns outros detalhes, mas deixa que eu faço isso, pq ta na minha cabeça aqui

2017-10-16 11:45 UTC, Vitormdias commented on src/router/index.js
> +    path: '/corrigirprova',
só /corrigir

2017-10-18 05:11 UTC, medson10 commented
![image](https://user-images.githubusercontent.com/17956325/31701858-ecfa5aa6-b3b1-11e7-9128-96e81fe8f72d.png)

2017-10-18 13:25 UTC, Vitormdias requested changes
Ficou bem legal, só tem algumas coisinhas

1 - tirar scroll do componente
2 - componente -> progresso
    - 0% - 40%  -> Vermelho
    - 40% - 70% -> Amarelo
    - > 70%     -> Verde
3 - Percentual Estimado um retangulo do tamanho do atual/2
4 - Nota real do tamanho do atual/2, talvez seja mais interessante
    colocar o texto e percentual um de cada lado
5 - botões pretos deixar azul
6 - Quantidade de alunos q faltam na primeira linha
    p. e. 1 / 30 do lado dos botões

2017-10-18 16:43 UTC, medson10 commented
![image](https://user-images.githubusercontent.com/17956325/31731031-84c8a094-b412-11e7-8102-e46655598335.png)

2017-10-18 16:45 UTC, medson10 commented
Não ta funcionando as properties para alterar a cor do progress, e não tem como o componente ficar sem scroll

2017-10-18 17:17 UTC, Vitormdias requested changes
7 - Botão de navegação um de cada lado e menor, quadrado
8 - Numero maior e texto em negrito nas percentagens
9 - Enunciado da questão em cima da resposta do aluno
10 - Alinhar texto Alunos Restantes com o resto
11 - Quando tiver selecionado a mostrar resposta, talvez seja melhor  scrolar, deixar o componente maior e tal

A questão das cores, a gente ve junto depois

2017-10-18 18:28 UTC, medson10 commented
![image](https://user-images.githubusercontent.com/17956325/31735647-4c929914-b421-11e7-8e0d-67c26bba7c02.png)

2017-10-18 18:28 UTC, medson10 commented
Não consegui aumentar o numero

2017-10-18 19:05 UTC, Vitormdias commented
Beleza, ta legal, fica só a questão das cores, ai depois eu vejo qualquer coisa, você pode ir pra outra task ja

2017-10-18 19:10 UTC, Vitormdias approved these changes

2017-10-18 19:10 UTC, merged