Feat/logica corrigir dialog
IC-TestIt/Front-End pull request #88
Opened 2017-10-20 13:47 UTC by medson10

2017-10-20 15:43 UTC, Vitormdias requested changes
Acho que é melhor fazer uma camada de persistencia separada da regra, tipo vc no storageModule deixa metodos genéricos, e em um examService as chamadas, dai acho q fica legal também fazer um refact onde usa local storage, ai da pra usar, no storage.local.save ou storage.session.save, fica melhor

2017-10-20 19:30 UTC, medson10 commented
Tentei alterar o auth para usar este modulo mas deu erro

2017-10-20 20:04 UTC, Vitormdias commented
Que erro?

2017-10-20 20:07 UTC, medson10 commented
Ta aparecendo os dois menus, então tem algo errado com a comparação com 0, ja verifiquei isso ta gravando certo, mas na hora de dar o get tem algo errado

2017-10-21 02:20 UTC, Vitormdias approved these changes

2017-10-21 02:22 UTC, merged