Feat/texto corrigir prova
IC-TestIt/Front-End pull request #94
Opened 2017-10-30 00:16 UTC by matheusnovais95

![image](https://user-images.githubusercontent.com/18332845/32150197-c7e6942a-bcf6-11e7-8aac-30be18e25eb4.png)

2017-10-30 11:34 UTC, Vitormdias requested changes
Cara essa tela já ta integrada, vc não pode deixar esses lorem ai né, e o texto ta preto ou azul?

2017-10-30 11:35 UTC, Vitormdias requested changes
Resolver conflitos

2017-10-30 11:35 UTC, Vitormdias commented on src/components/CorrectTests.vue
> +                        <p class="px-3 py-2 body-1 primary--text" box multi-line disabled label="" :value="currentQuestion.description">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
Deixar o texto que vem do back

2017-10-30 11:35 UTC, Vitormdias commented on src/components/CorrectTests.vue
> +                        <p class="px-3 py-2 body-1 primary--text" box multi-line disabled label="" :value="currentQuestion.description">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
não lorem

2017-10-30 11:37 UTC, Vitormdias commented
![](https://github.trello.services/images/mini-trello-icon.png) [Texto do conteudo principal mais legivel (Corrigir Prova)](https://trello.com/c/GsURnvPT/251-texto-do-conteudo-principal-mais-legivel-corrigir-prova)

2017-11-01 03:45 UTC, matheusnovais95 commented
![image](https://user-images.githubusercontent.com/18332845/32259253-4da63b82-bea6-11e7-902e-cdba91187b73.png)

2017-11-01 21:56 UTC, Vitormdias approved these changes

2017-11-01 21:57 UTC, Vitormdias commented
@matheusnovais95 corrigir os conflitos por favor

2017-11-03 20:07 UTC, Vitormdias requested changes
@matheusnovais95 resolve isso cara por favor, logo

2017-11-07 19:48 UTC, medson10 approved these changes

2017-11-07 19:50 UTC, Vitormdias approved these changes

2017-11-07 19:51 UTC, merged